url: "https://vpicave.club" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/" # the subpath of your site, e.g. /blog
title: "VPI Cave Club" # the name of your site, e.g. ACME Corp.
